# Generated by Django 6.0.8 on 2026-09-13 21:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bif_per_btc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source', models.CharField(default='manual', help_text='e.g. manual, coingecko, binance.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('lightning_invoice', 'Lightning Invoice'), ('lightning_address', 'Lightning Address'), ('lnurl', 'LNURL Pay'), ('bitcoin_address', 'Bitcoin Address')], max_length=40, unique=True)),
                ('display_label', models.CharField(max_length=80)),
                ('fixed_fee_sats', models.PositiveIntegerField(default=0)),
                ('percent_fee_bps', models.PositiveIntegerField(default=0, help_text='Percentage fee in basis points. 100 bps = 1%.')),
                ('min_fee_sats', models.PositiveIntegerField(default=0)),
                ('max_fee_sats', models.PositiveIntegerField(default=0, help_text='0 means no maximum cap.')),
                ('charge_to_user', models.BooleanField(default=False, help_text='When enabled, the fee is deducted from user balance in addition to the withdrawal amount.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Fee Policy',
                'verbose_name_plural': 'Withdrawal Fee Policies',
                'ordering': ['target_type'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_platform', models.BooleanField(db_index=True, default=False)),
                ('available_balance', models.BigIntegerField(default=0, help_text='Spendable BTC balance, in satoshis.')),
                ('pending_balance', models.BigIntegerField(default=0, help_text='Unconfirmed incoming BTC balance, in satoshis.')),
                ('locked_balance', models.BigIntegerField(default=0, help_text='Sats locked/escrowed, in satoshis.')),
                ('bif_balance', models.BigIntegerField(default=0, help_text='Spendable fiat balance, in whole Burundian Francs.')),
                ('total_deposited', models.BigIntegerField(default=0)),
                ('total_withdrawn', models.BigIntegerField(default=0)),
                ('total_rewarded', models.BigIntegerField(default=0)),
                ('bitcoin_address', models.CharField(blank=True, db_index=True, default='', help_text='On-chain Bitcoin deposit address generated for this user.', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POSCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_sats', models.BigIntegerField()),
                ('bif_equivalent', models.BigIntegerField()),
                ('rate_bif_per_btc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_hash', models.CharField(blank=True, db_index=True, default='', max_length=66)),
                ('payment_request', models.CharField(blank=True, default='', max_length=1000)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_charges', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmatoPayCheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='AmatoPay session_id (UUID).', max_length=64, unique=True)),
                ('payer_alias', models.CharField(max_length=160)),
                ('amount_bif', models.BigIntegerField()),
                ('checkout_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amatopay_sessions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('fee', 'Platform Fee'), ('exchange_sats_to_bif', 'Exchange: SATS → BIF'), ('exchange_bif_to_sats', 'Exchange: BIF → SATS'), ('bif_topup', 'BIF Top-up (AmatoPay)'), ('pos_settlement', 'POS Settlement (BIF)')], max_length=30)),
                ('currency', models.CharField(choices=[('sats', 'Satoshis'), ('bif', 'Burundian Franc')], default='sats', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('amount', models.BigIntegerField(help_text='Always positive; magnitude in `currency` units.')),
                ('balance_after', models.BigIntegerField(blank=True, null=True)),
                ('lnd_invoice', models.CharField(blank=True, default='', max_length=1000)),
                ('lnd_payment_hash', models.CharField(blank=True, db_index=True, default='', max_length=66)),
                ('onchain_address', models.CharField(blank=True, default='', max_length=120)),
                ('onchain_txid', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('network', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('linked_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('linked_object_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_wall_user_id_03e396_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_platform'], name='wallet_wall_is_plat_ae1614_idx'),
        ),
        migrations.AddIndex(
            model_name='poscharge',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_posc_wallet__592e94_idx'),
        ),
        migrations.AddIndex(
            model_name='poscharge',
            index=models.Index(fields=['payment_hash'], name='wallet_posc_payment_2f014b_idx'),
        ),
        migrations.AddIndex(
            model_name='amatopaycheckoutsession',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_amat_wallet__c22919_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_wall_wallet__ccf672_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_wall_status_66d39d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['type'], name='wallet_wall_type_12424b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['onchain_address'], name='wallet_wall_onchain_229f81_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['onchain_txid'], name='wallet_wall_onchain_6d9f6a_idx'),
        ),
    ]
