# Generated by Django 6.1.1 on 2026-09-13 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance', models.BigIntegerField(default=0, help_text='Spendable balance, in satoshis.')),
                ('pending_balance', models.BigIntegerField(default=0, help_text='Unconfirmed incoming balance, in satoshis.')),
                ('bitcoin_address', models.CharField(blank=True, default='', max_length=120)),
                ('lightning_address', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('amount_sats', models.BigIntegerField(help_text='Transaction amount in satoshis (always positive).')),
                ('balance_after', models.BigIntegerField(blank=True, null=True)),
                ('lightning_invoice', models.CharField(blank=True, default='', max_length=1000)),
                ('payment_hash', models.CharField(blank=True, db_index=True, default='', max_length=66)),
                ('onchain_address', models.CharField(blank=True, default='', max_length=120)),
                ('onchain_txid', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_tran_wallet__abbc5a_idx'), models.Index(fields=['status'], name='wallet_tran_status_a49b73_idx')],
            },
        ),
    ]
