# Generated by Django 6.0.8 on 2026-09-13 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinHDWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_root_xprv', models.TextField(help_text='Fernet-encrypted BIP32 root xprv.')),
                ('network', models.CharField(help_text='btclib network name this root key was created for.', max_length=20)),
                ('next_index', models.PositiveIntegerField(default=0, help_text='Next unused BIP44 address_index to derive.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bitcoin HD wallet (singleton)',
            },
        ),
        migrations.CreateModel(
            name='PlatformBitcoinAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=120, unique=True)),
                ('derivation_index', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(blank=True, default='', help_text='e.g. user-<wallet_id> or change.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['derivation_index'],
            },
        ),
    ]
