# Generated by Django 6.0.8 on 2026-09-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_bitcoinhdwallet_platformbitcoinaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('fee', 'Platform Fee'), ('exchange_sats_to_bif', 'Exchange: SATS to BIF'), ('bif_topup', 'BIF Top-up (AmatoPay)'), ('pos_settlement', 'POS Settlement (BIF)')], max_length=30),
        ),
    ]
