# Generated by Django 6.0.8 on 2026-09-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poscharge',
            name='amatopay_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_charge', to='wallet.amatopaycheckoutsession'),
        ),
        migrations.AddField(
            model_name='poscharge',
            name='charge_type',
            field=models.CharField(choices=[('sats_to_bif', 'Sats charge, BIF settlement'), ('bif_to_sats', 'BIF charge, sats settlement')], db_index=True, default='sats_to_bif', max_length=20),
        ),
        migrations.AddField(
            model_name='poscharge',
            name='payer_alias',
            field=models.CharField(blank=True, default='', help_text='Mobile money alias (BIF_TO_SATS only).', max_length=160),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('fee', 'Platform Fee'), ('exchange_sats_to_bif', 'Exchange: SATS to BIF'), ('exchange_bif_to_sats', 'Exchange: BIF to SATS'), ('bif_topup', 'BIF Top-up (AmatoPay)'), ('pos_settlement', 'POS Settlement (BIF)')], max_length=30),
        ),
    ]
