# Generated by Django 6.0.8 on 2026-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_poscharge_amatopay_session_poscharge_charge_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmatoPayWebhookEvent',
            fields=[
                ('id', models.CharField(help_text='AmatoPay event id, e.g. evt_...', max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payment_reference', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='amatopaycheckoutsession',
            name='order_number',
            field=models.CharField(blank=True, default='', help_text='Our order_number sent to AmatoPay.', max_length=64),
        ),
        migrations.AddField(
            model_name='amatopaycheckoutsession',
            name='payer_display_name',
            field=models.CharField(blank=True, default='', help_text='Resolved from AmatoPay.', max_length=160),
        ),
        migrations.AddField(
            model_name='amatopaycheckoutsession',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='AmatoPay payment_reference — correlates the browser return_url and webhooks to this session.', max_length=64),
        ),
    ]
