# Generated by Django 6.0.8 on 2026-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_amatopaywebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amatopaycheckoutsession',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, help_text="When the payer's six-digit release code was accepted by AmatoPay, releasing held funds to us.", null=True),
        ),
        migrations.AddField(
            model_name='amatopaycheckoutsession',
            name='payment_status',
            field=models.CharField(blank=True, default='', help_text='Latest raw AmatoPay Payment.status (paid/funds_held/delivery_pending/settled/...).', max_length=32),
        ),
    ]
