# Generated by Django 6.0.8 on 2026-10-05 10:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


_COIN_TYPE_BY_NETWORK = {"mainnet": 0}


def backfill_platform_addresses(apps, schema_editor):
    """Existing addresses were all legacy P2PKH at m/44'/coin'/0'/0/<index>; link
    deposit addresses to the wallet that holds them and mark change addresses."""
    BitcoinHDWallet = apps.get_model("wallet", "BitcoinHDWallet")
    PlatformBitcoinAddress = apps.get_model("wallet", "PlatformBitcoinAddress")
    Wallet = apps.get_model("wallet", "Wallet")

    hd_wallet = BitcoinHDWallet.objects.first()
    coin_type = _COIN_TYPE_BY_NETWORK.get(hd_wallet.network, 1) if hd_wallet else 1
    wallets_by_address = {w.bitcoin_address: w for w in Wallet.objects.exclude(bitcoin_address="")}

    for row in PlatformBitcoinAddress.objects.all():
        row.script_type = "p2pkh"
        row.derivation_path = f"m/44h/{coin_type}h/0h/0/{row.derivation_index}"
        row.purpose = "change" if row.label == "change" else "deposit"
        row.wallet = wallets_by_address.get(row.address)
        row.save(update_fields=["script_type", "derivation_path", "purpose", "wallet"])


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_amatopaycheckoutsession_delivery_confirmed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BitcoinUTXO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("txid", models.CharField(max_length=64)),
                ("vout", models.PositiveIntegerField()),
                (
                    "value",
                    models.BigIntegerField(help_text="Output value in satoshis."),
                ),
                (
                    "block_height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Null while unconfirmed.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unspent", "Unspent"),
                            ("reserved", "Reserved by a withdrawal"),
                            ("spent", "Spent"),
                            ("dropped", "Dropped from mempool"),
                        ],
                        db_index=True,
                        default="unspent",
                        max_length=10,
                    ),
                ),
                (
                    "spent_by_txid",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-first_seen_at"],
            },
        ),
        migrations.AddField(
            model_name="platformbitcoinaddress",
            name="derivation_path",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="platformbitcoinaddress",
            name="purpose",
            field=models.CharField(
                choices=[("deposit", "User deposit"), ("change", "Withdrawal change")],
                default="deposit",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="platformbitcoinaddress",
            name="script_type",
            field=models.CharField(
                choices=[
                    ("p2pkh", "Legacy (P2PKH)"),
                    ("p2wpkh", "Native SegWit (P2WPKH)"),
                ],
                default="p2pkh",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="platformbitcoinaddress",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of a deposit address; deposits to it are credited to this wallet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bitcoin_addresses",
                to="wallet.wallet",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="network_fee_sats",
            field=models.BigIntegerField(
                default=0,
                help_text="Miner fee paid by the platform for an on-chain withdrawal.",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="onchain_raw_tx",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Signed raw transaction of an on-chain withdrawal, kept so it can be rebroadcast.",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="onchain_vout",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Output index of an on-chain deposit — one transaction can pay several outputs/users.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("onchain_vout__isnull", False), ("type", "deposit")
                ),
                fields=("onchain_txid", "onchain_vout"),
                name="unique_onchain_deposit_output",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinutxo",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utxos",
                to="wallet.platformbitcoinaddress",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinutxo",
            name="reserved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_utxos",
                to="wallet.wallettransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="bitcoinutxo",
            index=models.Index(
                fields=["status", "block_height"], name="wallet_bitc_status_a17213_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bitcoinutxo",
            constraint=models.UniqueConstraint(
                fields=("txid", "vout"), name="unique_bitcoin_outpoint"
            ),
        ),
        migrations.RunPython(backfill_platform_addresses, migrations.RunPython.noop),
    ]
