# Generated by Django 6.0.8 on 2026-10-05 11:03

import uuid
from django.db import migrations, models

# Copied (not imported) so this migration never changes when the code does.
SEED_PROVIDERS = [
    ("mainnet", "Blockstream", "https://blockstream.info/api", "https://blockstream.info", 10),
    ("mainnet", "mempool.space", "https://mempool.space/api", "https://mempool.space", 20),
    ("testnet4", "mempool.space", "https://mempool.space/testnet4/api", "https://mempool.space/testnet4", 10),
    ("testnet", "Blockstream", "https://blockstream.info/testnet/api", "https://blockstream.info/testnet", 10),
    ("testnet", "mempool.space", "https://mempool.space/testnet/api", "https://mempool.space/testnet", 20),
    ("signet", "Blockstream", "https://blockstream.info/signet/api", "https://blockstream.info/signet", 10),
    ("signet", "mempool.space", "https://mempool.space/signet/api", "https://mempool.space/signet", 20),
]


def seed_providers(apps, schema_editor):
    Provider = apps.get_model("wallet", "BlockExplorerProvider")
    for network, name, api_url, web_url, priority in SEED_PROVIDERS:
        Provider.objects.get_or_create(
            network=network, api_url=api_url,
            defaults={"name": name, "web_url": web_url, "priority": priority},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_onchain_utxo_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockExplorerProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mainnet", "Mainnet"),
                            ("testnet4", "Testnet4"),
                            ("testnet", "Testnet3"),
                            ("signet", "Signet"),
                            ("regtest", "Regtest"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        help_text="Esplora API base URL, e.g. https://mempool.space/testnet4/api (no trailing slash).",
                        max_length=300,
                    ),
                ),
                (
                    "web_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional explorer website for 'view transaction' links, e.g. https://mempool.space/testnet4.",
                        max_length=300,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower is tried first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=15, help_text="Read timeout per request."
                    ),
                ),
                (
                    "auth_header",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional header name for a private/paid instance, e.g. Authorization or X-API-Key.",
                        max_length=60,
                    ),
                ),
                (
                    "auth_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Value sent in that header, e.g. 'Bearer <token>'. Never shown in lists.",
                        max_length=300,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_ok", models.BooleanField(blank=True, null=True)),
                (
                    "last_check_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("last_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("last_tip_height", models.PositiveIntegerField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("total_requests", models.PositiveBigIntegerField(default=0)),
                ("total_failures", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["network", "priority", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("network", "api_url"),
                        name="unique_provider_url_per_network",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_providers, migrations.RunPython.noop),
    ]
